# https://github.com/probot/settings

branches:
  - name: "main"

    # https://developer.github.com/v3/repos/branches/#remove-branch-protection
    # https://developer.github.com/v3/repos/branches/#update-branch-protection

    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_status_checks:
        contexts:
          - "Code Coverage (7.4, locked)"
          - "Coding Standards (7.1, locked)"
          - "Compile Phar (7.4, locked)"
          - "Dependency Analysis (7.4, locked)"
          - "Label"
          - "Static Code Analysis (7.4, locked)"
          - "Static Code Analysis (7.4, locked)"
          - "Tests (7.1, 1, highest)"
          - "Tests (7.1, 1, locked)"
          - "Tests (7.1, 1, lowest)"
          - "Tests (7.1, 2, highest)"
          - "Tests (7.1, 2, locked)"
          - "Tests (7.1, 2, lowest)"
          - "Tests (7.2, 1, highest)"
          - "Tests (7.2, 1, locked)"
          - "Tests (7.2, 1, lowest)"
          - "Tests (7.2, 2, highest)"
          - "Tests (7.2, 2, locked)"
          - "Tests (7.2, 2, lowest)"
          - "Tests (7.3, 1, highest)"
          - "Tests (7.3, 1, locked)"
          - "Tests (7.3, 1, lowest)"
          - "Tests (7.3, 2, highest)"
          - "Tests (7.3, 2, locked)"
          - "Tests (7.3, 2, lowest)"
          - "Tests (7.4, 1, highest)"
          - "Tests (7.4, 1, locked)"
          - "Tests (7.4, 1, lowest)"
          - "Tests (7.4, 2, highest)"
          - "Tests (7.4, 2, locked)"
          - "Tests (7.4, 2, lowest)"
        strict: false
      restrictions:

        # https://developer.github.com/v3/repos/branches/#parameters-1

        # Note: User, app, and team restrictions are only available for organization-owned repositories.
        # Set to null to disable when using this configuration for a repository on a personal account.

        apps: []
        teams: []
        users:
          - "ergebnis-bot"

# https://developer.github.com/v3/issues/labels/#create-a-label
# https://developer.github.com/v3/issues/labels/#update-a-label

labels:
  - name: "bug"
    color: "ee0701"
    description: ""

  - name: "dependency"
    color: "0366d6"
    description: ""

  - name: "enhancement"
    color: "0e8a16"
    description: ""

  - name: "merge"
    color: "6f42c1"
    description: ""

  - name: "question"
    color: "cc317c"
    description: ""

  - name: "security"
    color: "ee0701"
    description: ""

  - name: "stale"
    color: "eeeeee"
    description: ""

# https://developer.github.com/v3/repos/#edit

repository:
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: false
  archived: false
  default_branch: "main"
  delete_branch_on_merge: true
  description: ":musical_note: Provides a composer plugin for normalizing composer.json."
  has_downloads: true
  has_issues: true
  has_pages: false
  has_projects: false
  has_wiki: false
  name: "composer-normalize"
  private: false

  # https://developer.github.com/v3/repos/branches/#remove-branch-protection

  topics: "composer, composer-plugin, json, normalizer"
