# https://github.com/probot/settings

branches:
  - name: 1.x
    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_status_checks:
        contexts:
          - "Coding Standards (7.2)"
          - "Dependency Analysis (7.3)"
          - "Static Code Analysis (7.3)"
          - "Tests (7.2, lowest)"
          - "Tests (7.2, locked)"
          - "Tests (7.2, highest)"
          - "Tests (7.3, lowest)"
          - "Tests (7.3, locked)"
          - "Tests (7.3, highest)"
          - "Code Coverage (7.3)"
          - "Mutation Tests (7.3)"
          - "codecov/patch"
          - "codecov/project"
        strict: false
      restrictions: null

labels:
  - name: bug
    color: ee0701

  - name: dependency
    color: 0366d6

  - name: enhancement
    color: 0e8a16

  - name: question
    color: cc317c

  - name: security
    color: ee0701

  - name: stale
    color: eeeeee

repository:
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: false
  default_branch: 1.x
  description: ":musical_note: Provides a composer plugin for normalizing composer.json."
  has_downloads: true
  has_issues: true
  has_pages: false
  has_projects: false
  has_wiki: false
  name: composer-normalize
  private: false
