# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - automerged_updates:
      - match:
          dependency_type: "development"
    default_assignees:
      - "localheinz"
    default_labels:
      - "dependency"
    default_reviewers:
      - "localheinz"
    directory: "/"
    ignored_updates:
      - match:
          dependency_name: "composer-plugin-api"
      - match:
          dependency_name: "composer/composer"
    package_manager: "php:composer"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
