# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:
    branches:
      - master
      - "1.x"
    tags:
      - "**"

name: "Continuous Integration"

jobs:
  coding-standards:
    name: "Coding Standards"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.2

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v1
        with:
          coverage: none
          extension-csv: "mbstring"
          php-version: ${{ matrix.php-version }}

      - name: "Validate composer.json and composer.lock"
        run: composer validate --strict

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-locked-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-locked-

      - name: "Install locked dependencies with composer"
        run: composer install --no-interaction --no-progress --no-suggest

      - name: "Run localheinz/composer-normalize"
        uses: docker://localheinz/composer-normalize-action:0.5.2
        with:
          args: --dry-run

      - name: "Create cache directory for friendsofphp/php-cs-fixer"
        run: mkdir -p .build/php-cs-fixer

      - name: "Cache cache directory for friendsofphp/php-cs-fixer"
        uses: actions/cache@v1
        with:
          path: ~/.build/php-cs-fixer
          key: php${{ matrix.php-version }}-php-cs-fixer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php${{ matrix.php-version }}-php-cs-fixer-

      - name: "Run friendsofphp/php-cs-fixer"
        run: vendor/bin/php-cs-fixer fix --config=.php_cs --diff --diff-format=udiff --dry-run --verbose

  dependency-analysis:
    name: "Dependency Analysis"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.3

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v1
        with:
          coverage: none
          extension-csv: "mbstring"
          php-version: ${{ matrix.php-version }}

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-locked-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-locked-

      - name: "Install locked dependencies with composer"
        run: composer install --no-interaction --no-progress --no-suggest

      - name: "Run maglnet/composer-require-checker"
        uses: docker://localheinz/composer-require-checker-action:1.1.0
        with:
          args: --config-file=composer-require-checker.json

  static-code-analysis:
    name: "Static Code Analysis"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.3

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v1
        with:
          coverage: none
          extension-csv: "mbstring"
          php-version: ${{ matrix.php-version }}

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ matrix.php-version }}-composer-locked-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ matrix.php-version }}-composer-locked-

      - name: "Install locked dependencies with composer"
        run: composer install --no-interaction --no-progress --no-suggest

      - name: "Run phpstan/phpstan"
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon

  tests:
    name: "Tests"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.2
          - 7.3

        dependencies:
          - lowest
          - locked
          - highest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v1
        with:
          coverage: none
          extension-csv: "mbstring"
          php-version: ${{ matrix.php-version }}

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-

      - name: "Install lowest dependencies with composer"
        if: matrix.dependencies == 'lowest'
        run: composer update --no-interaction --no-progress --no-suggest --prefer-lowest

      - name: "Install locked dependencies with composer"
        if: matrix.dependencies == 'locked'
        run: composer install --no-interaction --no-progress --no-suggest

      - name: "Install highest dependencies with composer"
        if: matrix.dependencies == 'highest'
        run: composer update --no-interaction --no-progress --no-suggest

      - name: "Run integration tests with phpunit/phpunit"
        run: vendor/bin/phpunit --configuration=test/Integration/phpunit.xml

  code-coverage:
    name: "Code Coverage"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.3

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v1
        with:
          coverage: xdebug
          extension-csv: "mbstring"
          php-version: ${{ matrix.php-version }}

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-locked-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-locked-

      - name: "Install locked dependencies with composer"
        run: composer install --no-interaction --no-progress --no-suggest

      - name: "Dump Xdebug filter with phpunit/phpunit"
        run: vendor/bin/phpunit --configuration=test/Integration/phpunit.xml --dump-xdebug-filter=.build/phpunit/xdebug-filter.php

      - name: "Collect code coverage with Xdebug and phpunit/phpunit"
        run: vendor/bin/phpunit --configuration=test/Integration/phpunit.xml --coverage-clover=build/logs/clover.xml --prepend=.build/phpunit/xdebug-filter.php

      - name: "Send code coverage report to Codecov.io"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
