# https://docs.github.com/en/actions

name: "Merge"

on: # yamllint disable-line rule:truthy
  workflow_run:
    types:
      - "completed"
    workflows:
      - "Integrate"

jobs:
  merge:
    name: "Merge"

    runs-on: "ubuntu-latest"

    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.actor == 'dependabot[bot]' && (
        startsWith(github.event.workflow_run.head_commit.message, 'composer(deps-dev)') ||
        startsWith(github.event.workflow_run.head_commit.message, 'github-actions(deps)')
      )

    steps:
      - name: "Request review from @ergebnis-bot"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0];

            const reviewers = [
              "ergebnis-bot",
            ];

            try {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                pull_number: pullRequest.number,
                repo: context.repo.repo,
                reviewers: reviewers,
              });
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: "Assign @ergebnis-bot"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0];

            const assignees = [
              "ergebnis-bot",
            ];

            try {
              await github.rest.issues.addAssignees({
                assignees: assignees,
                issue_number: pullRequest.number
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: "Approve pull request"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0];

            try {
              await github.rest.pulls.createReview({
                event: "APPROVE",
                owner: context.repo.owner,
                pull_number: pullRequest.number,
                repo: context.repo.repo,
              });
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: "Merge pull request"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0];

            try {
              await github.rest.pulls.merge({
                merge_method: "merge",
                owner: context.repo.owner,
                pull_number: pullRequest.number,
                repo: context.repo.repo,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
