# https://docs.github.com/en/actions

name: "Renew"

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 1 1 *"

env:
  PHP_EXTENSIONS: "mbstring"
  PHP_INI_VALUES: "memory_limit=-1, phar.readonly=0"

jobs:
  license:
    name: "License"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.2"

        dependencies:
          - "locked"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.4"
        with:
          token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@2.10.0"
        with:
          coverage: "none"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          ini-values: "${{ env.PHP_INI_VALUES }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --strict"

      - name: "Determine composer cache directory"
        uses: "./.github/actions/composer/composer/determine-cache-directory"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.1.4"
        with:
          path: "${{ env.COMPOSER_CACHE_DIR }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install ${{ matrix.dependencies }} dependencies with composer"
        uses: "./.github/actions/composer/composer/install"
        with:
          dependencies: "${{ matrix.dependencies }}"

      - name: "Create cache directory for friendsofphp/php-cs-fixer"
        run: "mkdir -p .build/php-cs-fixer"

      - name: "Cache cache directory for friendsofphp/php-cs-fixer"
        uses: "actions/cache@v2.1.4"
        with:
          path: ".build/php-cs-fixer"
          key: "php-${{ matrix.php-version }}-php-cs-fixer-${{ github.sha }}"
          restore-keys: "php-${{ matrix.php-version }}-php-cs-fixer-"

      - name: "Run friendsofphp/php-cs-fixer"
        run: "vendor/bin/php-cs-fixer fix --config=.php_cs --diff --diff-format=udiff --verbose"

      - name: "Commit modified files"
        uses: "stefanzweifel/git-auto-commit-action@v4.10.0"
        with:
          commit_author: "ergebnis-bot <bot@ergebn.is>"
          commit_message: "Enhancement: Update license year"
          commit_user_email: "bot@ergebn.is"
          commit_user_name: "ergebnis-bot"
